### PR TITLE
Added greek language (Ελλινικά)

### PR DESCRIPTION
**Pull request by bopv2**
Useless but still it is something :D
**Some strings havent changed cause i dont know how to explain them in greek**

### CODE REVIEW

**Comment by 4yx** [comment]
> Useless but still it is something :D

Not useless at all :D, as another Greek that was planning on working on a translation I thank you for your work.
There are a few typos I'll fix in a PR and I'll try to find a translation for the strings you could not if I can, but in any case you're awesome, thanks again!

**Comment by mahtab2003** [comment]
you are welcome

**Comment by bopv2** [comment]
> > Useless but still it is something :D
> 
> Not useless at all :D, as another Greek that was planning on working on a translation I thank you for your work. There are a few typos I'll fix in a PR and I'll try to find a translation for the strings you could not if I can, but in any case you're awesome, thanks again!

Thanks for fixing it up!

**Comment by 4yx** [comment]
Sorry, it took me way longer than expected because I couldn't get a working installation. I finally managed to get one, and will be testing how the translation looks and making a PR soon.

**Comment by mahtab2003** [comment]
oh ok

**Pull request merged**
